---
title: "Figures for Manuscript"
author: "Aris Paschalidis"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = FALSE
)

library(coiaf)
library(ggplot2)
library(patchwork)
```

## Flowchart of Methods
```{r initialize PLAF}
# Set seed
set.seed(1)

# Define the number of loci and the distribution of minor allele frequencies
L <- 1000
p <- stats::rbeta(L, 1, 5)
p[p > 0.5] <- 1 - p[p > 0.5]
```

```{r data points for methods}
set.seed(30)
sim <- sim_biallelic(coi = 4, plmaf = p, coverage = 400)
plot_data <- sim$data %>% 
  dplyr::mutate(homo = ifelse(sim$data$wsmaf <= 0 | sim$data$wsmaf >= 1, TRUE, FALSE))
  

# All data
data_points <- ggplot() +
  geom_point(data = plot_data, aes(x = plmaf, y = wsmaf, color = homo)) +
  scale_colour_discrete(
    name = "", 
    type = c("#242F40", "#CCA43B"), 
    labels = c("Heterozygous Loci", "Homozygous Loci")
  ) +
  theme_coiaf() +
  labs(x = "PLMAF", y = "WSMAF", title = "All Data Points")

# Variant data
variant <- ggplot() +
  geom_point(
    data = dplyr::mutate(
      plot_data, 
      wsmaf = ifelse(sim$data$wsmaf <= 0 | sim$data$wsmaf >= 1, 0, 1)
    ),
    aes(x = plmaf, y = wsmaf, color = homo), 
  ) +
  scale_colour_discrete(
    name = "", 
    type = c("#242F40", "#CCA43B"), 
    labels = c("Heterozygous Loci", "Homozygous Loci")
  ) +
  theme_coiaf() +
  labs(x = "PLMAF", y = "Variant Site", title = "Variants")

# Heterozygous data
het <- ggplot() +
  geom_point(
    data = dplyr::filter(plot_data, !homo),
    aes(x = plmaf, y = wsmaf), 
    color = "#242F40"
  ) +
  theme_coiaf() +
  labs(x = "PLMAF", y = "WSMAF", title = "Heterozygous Data")
```

```{r figures with theoretical and true lines}
# Processed Variant Method
process_variant <- process_sim(sim, coi_method = "variant", bin_size = 50)

variant_final <- ggplot() +
  geom_point(
    data = dplyr::mutate(
      plot_data, 
      wsmaf = ifelse(sim$data$wsmaf <= 0 | sim$data$wsmaf >= 1, 0, 1)
    ),
    aes(x = plmaf, y = wsmaf, color = homo), 
  ) +
  geom_line(aes(x = p, y = 1 - p^1 - (1 - p)^1), color = "#E55934", linetype = 2) +
  geom_line(aes(x = p, y = 1 - p^2 - (1 - p)^2), color = "#E55934", linetype = 2) +
  geom_line(aes(x = p, y = 1 - p^3 - (1 - p)^3), color = "#E55934", linetype = 2) +
  geom_line(aes(x = p, y = 1 - p^4 - (1 - p)^4), color = "#E55934", linetype = 2) +
  annotate(
    geom = "text", x = 0.47, y = 1 - 0.5^(0:1) + 0.05,
    label = c("COI = 1", "COI = 2"), col = "#FF1B1C", size = 7 / .pt
  ) +
  annotate(
    geom = "text", x = 0.47, y = 1 - 0.5^(2:3) - 0.025,
    label = c("COI = 3", "COI = 4"), col = "#E55934", size = 7 / .pt
  ) +
  scale_colour_discrete(
    name = "", 
    type = c("#242F40", "#CCA43B"), 
    labels = c("Heterozygous Loci", "Homozygous Loci")
  ) +
  theme_coiaf() +
  theme(axis.title.y.right = element_text(color = "#E55934")) +
  labs(x = "PLMAF", y = "Variant Site", title = "Variant Method")

# Processed Frequency Method
process_freq <- process_sim(sim, coi_method = "frequency", bin_size = 50)

freq_final <- ggplot() +
  geom_point(
    data = dplyr::filter(plot_data, !homo),
    aes(x = plmaf, y = wsmaf), 
    color = "#242F40"
  ) +
  geom_line(aes(x = p, y = (p - p^2) / (1 - p^2 - (1 - p)^2)),
    color = "#E55934", linetype = 2
  ) +
  geom_line(aes(x = p, y = (p - p^3) / (1 - p^3 - (1 - p)^3)),
    color = "#E55934", linetype = 2
  ) +
  geom_line(aes(x = p, y = (p - p^4) / (1 - p^4 - (1 - p)^4)),
    color = "#E55934", linetype = 2
  ) +
  annotate(
    geom = "text", x = 0.01, y = 1 / 3:4 + 0.03,
    label = c("COI = 3", "COI = 4"), col = "#E55934",
    size = 7 / .pt, angle = "8"
  ) +
  annotate(
    geom = "text", x = 0.02, y = 1 / 2 + 0.04,
    label = c("COI = 2"), col = "#E55934", size = 7 / .pt
  ) +
  theme_coiaf() +
  # guides(color = "none") +
  theme(axis.title.y.right = element_text(color = "#E55934")) +
  labs(x = "PLMAF", y = "WSMAF", title = "Frequency Method")
```

```{r figure 1}
plot <- (plot_spacer() +
  data_points +
  plot_spacer() +
  plot_layout(widths = c(1, 3, 1))
) /
  (variant | het) /
  (variant_final | freq_final) +
  plot_layout(guides = "collect") +
  plot_annotation(tag_levels = "A") &
  theme(
    plot.tag = element_text(face = "bold"),
    legend.position = "bottom"
  )

plot
```

```{r save fig 1, eval = FALSE}
ggsave(
  filename = here::here("misc-figures", "methods-flowchart.png"),
  device = "png",
  width = 2000,
  height = 1800,
  units = "px",
  dpi = "print"
)
```

## Case Study of Increased Variance
```{r eval = FALSE}
# We must first extract the wsaf and plaf for our sample of interest
# We look at sample PA0454-C
# After extracting said data, we can run the following to generate our figure

data = data.frame(wsaf = wsaf, plaf = plaf)

full <- ggplot() +
  geom_point(data = data, aes(x = plaf, y = wsaf), alpha = 0.5) +
  mytheme +
  labs(x = "PLAF", y = "WSAF", title = "All Loci")

data_sub <- data %>% dplyr::filter(wsaf > seq_error & wsaf < (1 - seq_error))

subset <- ggplot() +
  geom_point(data = data_sub, aes(x = plaf, y = wsaf), alpha = 0.5) +
  mytheme +
  labs(x = "PLAF", y = "WSAF", title = "Heterozygous Loci")

ggpubr::ggarrange(full, subset,
                  ncol = 2,
                  labels = "AUTO",
                  font.label = list(size = 10))
```

## Bootstrapped Confidence Interval
```{r bootstrapped ci}
plot_list <- list()

for (i in 2:10) {
  set.seed(500)
  sim_data <- sim_biallelic(coi = i, plmaf = runif(1000, 0, 0.5))
  ci <- bootstrap_ci(
    sim_data, 
    solution_method = "continuous",
    replicates = 1000,
    parallel = TRUE,
    ncpus = 12
  )

  coi_estimates <- tibble::enframe(unlist(ci$estimates))

  plot <- ggplot(coi_estimates, aes(x = value)) +
    geom_density(fill = "gray", alpha = 0.5) +
    # geom_histogram(fill = "gray", alpha = 0.5) +
    # shade_confidence_interval(endpoints = c(4.24, 5.12)) +
    labs(x = "Estimated COI", y = "Density", title = paste("True COI =", i)) +
    theme_coiaf()

  plot_list <- c(plot_list, list(plot))
}

patchwork::wrap_plots(plot_list) +
  patchwork::plot_annotation(
    tag_levels = "A",
    theme = theme(plot.tag = element_text(size = 10))
  ) +
  theme(legend.position = "bottom") &
  theme(plot.tag = element_text(face = "bold"))

ggsave(
  filename = here::here("misc-figures", "bootstrapped_ci.png"),
  device = "png", 
  width = 2000, 
  height = 1750, 
  units = "px", 
  dpi = "print"
)
```

## Unbiased PLMAF

```{r}
suppressMessages(library(tidyverse))

# function to estimate p_i based on distribution of cois and the true_pi
estimate_plmaf <- function(true_plmaf, max_coi, samples) {
  cois <- sample(seq_len(max_coi), samples, replace = TRUE)

  # for these, how many have the minor allele
  n_i <- rbinom(samples, cois, true_plmaf)

  # draw random proportions for the sum of the strain proportions that are minor
  # allele i.e. this is the Beta distribution, with alpha being proportion of
  # strains that have minor allele and beta being 1-this
  s_i_c_i <- rbeta(samples, n_i / cois, (cois - n_i) / cois)

  # the mean across our samples is unbiased estimator of p_i
  mean(s_i_c_i)
}

# Define parameter grid
par_grid <- expand.grid(
  samples = c(10, 50, 100, 250, 500, 1000),
  true_plmaf = c(0.01, 0.025, 0.05, 0.1, 0.25, 0.5),
  max_coi = c(2:10),
  rep = 1:50
)

par_grid <- par_grid %>% 
  rowwise() %>% 
  mutate(plmaf = estimate_plmaf(true_plmaf, max_coi, samples))
```


```{r using bernoulli and dirichlet}
suppressMessages(library(tidyverse))

# function to estimate p_i based on distribution of cois and the true_pi
estimate_plmaf <- function(true_plmaf, max_coi, samples, alpha) {
  cois <- sample(seq_len(max_coi), samples, replace = TRUE)

  wsmafs <- c()
  for (j in cois) {
    # draw from Bernoulli to find which strains have minor
    c_j <- rbinom(j, 1, true_plmaf)
    
    # draw strain proportions from Dirichlet
    s_j <- coiaf:::rdirichlet(rep(alpha, j))
    
    # find wsmaf by summing the product
    w_i <- sum(c_j * s_j)
    wsmafs <- c(wsmafs, w_i)
  }

  # the mean across our samples is unbiased estimator of p_i
  mean(wsmafs, na.rm = TRUE)
}

# Define parameter grid
par_grid <- expand.grid(
  samples = c(10, 50, 100, 250, 500, 1000),
  true_plmaf = c(0.01, 0.025, 0.05, 0.1, 0.25, 0.5),
  max_coi = c(2:10),
  alpha = seq(0.01, 0.1, 0.01),
  rep = 1:50
)

par_grid <- par_grid %>% 
  rowwise() %>% 
  mutate(plmaf = estimate_plmaf(true_plmaf, max_coi, samples, alpha))
```

```{r plot unbiased PLMAF}
par_grid %>%
  group_by(samples, true_plmaf, max_coi, alpha) %>%
  summarise(
    low = quantile(plmaf, 0.025),
    high = quantile(plmaf, 0.975),
    plmaf = median(plmaf),
    .groups = "drop"
  ) %>%
  mutate(true_plmaf_desc = paste0("True PLMAF = ", true_plmaf)) %>%
  ggplot(aes(
    x = samples,
    y = plmaf,
    color = max_coi,
    ymin = low,
    ymax = high
  )) +
  geom_hline(aes(yintercept = true_plmaf), linetype = "dashed") +
  geom_pointrange() +
  facet_wrap(~true_plmaf_desc, scales = "free_y") +
  scale_x_log10() +
  labs(x = "Number of Samples", y = "Observed PLMAF") +
  scale_color_continuous(name = "Max COI") +
  theme_coiaf()

ggsave(
  filename = here::here("misc-figures", "unbiased_plmaf.png"),
  device = "png", 
  width = 2000, 
  height = 1750, 
  units = "px", 
  dpi = "print"
)
```
