---
title: "Benchmarks"
author: "Aris Paschalidis"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

library(coiaf)
library(patchwork)
```

# Comparing coiaf methods

| Variant Method | Frequency Method |
| :------------: | :--------------: |
| Discrete       | Discrete         |
| Continuous     | Continuous       |

```{r function definitions}
# Set seed
# set.seed(101)

# Create function to take variable COI and # of loci
create_data <- function(coi, n_loci) {
  plmaf <- stats::rbeta(n_loci, 1, 5)
  plmaf[plmaf > 0.5] <- 1 - plmaf[plmaf > 0.5]

  sim_biallelic(coi = coi, plmaf = plmaf)
}
```

```{r bench fns, include = FALSE}
bench_plot <- function(bench, title = NULL) {
  bench <- dplyr::rename(bench, Loci = n_loci, COI = coi)

  ggplot2::autoplot(bench, show.legend = TRUE, alpha = 0.8) +
    theme_coiaf() +
    ggplot2::labs(y = "Time", x = "Estimation Method", title = title) +
    ggplot2::scale_color_discrete(
      name = "Garbage Collection",
      labels = c("None", "Level 0", "Level 1", "Level 2")
    ) +
    ggplot2::theme(legend.title = ggplot2::element_text(hjust = 0.5)) +
    ggplot2::guides(x = ggplot2::guide_axis(angle = 45))
}

bench_stats <- function(bench) {
  bench <- dplyr::rename(bench, Loci = n_loci, COI = coi)

  stats <- bench %>%
    dplyr::select(expression, COI, Loci, time) %>%
    dplyr::mutate(expression = as.character(expression)) %>% 
    dplyr::filter(COI != 1)

  if ("Discrete" %in% stats$expression) {
    discrete <- stats %>%
      dplyr::filter(expression == "Discrete") %>%
      dplyr::pull(time) %>% 
      unlist()

    continuous <- stats %>%
      dplyr::filter(expression != "Discrete") %>%
      dplyr::pull(time) %>% 
      unlist()

    pvalue <- wilcox.test(discrete, continuous, paired = TRUE)$p.value
    means <- c(discrete = mean(discrete), continuous = mean(continuous))
  } else if ("Variant" %in% stats$expression) {
    variant <- stats %>%
      dplyr::filter(expression == "Variant") %>%
      dplyr::pull(time) %>% 
      unlist()

    frequency <- stats %>%
      dplyr::filter(expression != "Variant") %>%
      dplyr::pull(time) %>% 
      unlist()

   pvalue <- wilcox.test(variant, frequency, paired = TRUE)$p.value
   means <- c(variant = mean(variant), frequency = mean(frequency))
  }
  
  c(format(means, scientific = FALSE), pvalue = pvalue)
}
```

```{r disc vs cont variant method}
bench_var <- bench::press(
  coi = c(1, seq(5, 25, 5)),
  n_loci = c(100, 1000, 5000, 10000),
  {
    dat <- create_data(coi, n_loci)
    bench::mark(
      min_iterations = 100,
      Discrete = compute_coi(dat, "sim"),
      Continuous = optimize_coi(dat, "sim"),
      check = FALSE
    )
  }
)

bench_plot(bench_var)
bench_stats(bench_var)
```

```{r disc vs cont freq method}
bench_freq <- bench::press(
  coi = c(1, seq(5, 25, 5)),
  n_loci = c(100, 1000, 5000, 10000),
  {
    dat <- create_data(coi, n_loci)
    bench::mark(
      min_iterations = 100,
      Discrete = compute_coi(dat, "sim", coi_method = "frequency"),
      Continuous = optimize_coi(dat, "sim", coi_method = "frequency"),
      check = FALSE
    )
  }
)

bench_plot(bench_freq)
bench_stats(bench_freq)
```

```{r combine discrete vs continuous plots}
bench_plot(bench_var) + bench_plot(bench_freq) +
  plot_layout(guides = "collect") +
  plot_annotation(
    tag_levels = "A",
    theme = theme(plot.tag = element_text(size = 10))
  ) &
  theme(plot.tag = element_text(face = "bold")) &
  theme(legend.position = "bottom")

ggsave(
  filename = here::here("benchmarking", "bench-images", "bench-soln-methods.png"),
  device = "png", 
  width = 2500, 
  height = 1500, 
  units = "px", 
  dpi = "print"
)
```


```{r var vs freq discrete}
bench_dis <- bench::press(
  coi = c(1, seq(5, 25, 5)),
  n_loci = c(100, 1000, 5000, 10000),
  {
    dat <- create_data(coi, n_loci)
    bench::mark(
      min_iterations = 100,
      Variant = compute_coi(dat, "sim", coi_method = "variant"),
      Frequency = compute_coi(dat, "sim", coi_method = "frequency"),
      check = FALSE
    )
  }
)

bench_plot(bench_dis)
bench_stats(bench_dis)
```

```{r var vs freq discrete}
bench_cont <- bench::press(
  coi = c(1, seq(5, 25, 5)),
  n_loci = c(100, 1000, 5000, 10000),
  {
    dat <- create_data(coi, n_loci)
    bench::mark(
      min_iterations = 100,
      Variant = optimize_coi(dat, "sim", coi_method = "variant"),
      Frequency = optimize_coi(dat, "sim", coi_method = "frequency"),
      check = FALSE
    )
  }
)

bench_plot(bench_cont)
bench_stats(bench_cont)
```

```{r combine discrete vs continuous plots}
bench_plot(bench_dis) + bench_plot(bench_cont) +
  plot_layout(guides = "collect") +
  plot_annotation(
    tag_levels = "A",
    theme = theme(plot.tag = element_text(size = 10))
  ) &
  theme(plot.tag = element_text(face = "bold")) &
  theme(legend.position = "bottom")

ggsave(
  filename = here::here("benchmarking", "bench-images", "bench-estim-methods.png"),
  device = "png", 
  width = 2500, 
  height = 1500, 
  units = "px", 
  dpi = "print"
)
```

From these results, we can see that for small numbers of loci, the discrete
method is almost twice as fast as the continuous method. However, as the number
of loci increases, this difference becomes smaller.
